name: Add comment to PR with "stacked/*" branch

on:
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get files changed
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Get the first file changed
          FIRST_FILE=$(echo "$FILES_CHANGED" | head -n 1)

          echo "::set-output name=first_file::$FIRST_FILE"
